//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDislikedPost
    {
        public int ID { get; set; }
        public Nullable<int> PostID { get; set; }
        public string UserID { get; set; }
        public string PostTitle { get; set; }
    }
}
